version: "3"

services:
  web:
    container_name: web
    build:
      context: ./docker/web
    tty: true
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html:rw
      - ./cgi-bin:/var/www/cgi-bin:rw
  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:8.0
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - ./docker/db/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  mail:
    container_name: ${MAIL_CONTAINER_NAME}
    image: mailhog/mailhog
    ports:
      - ${MAIL_HTTP_PORT}:${MAIL_HTTP_PORT}
      - ${MAIL_SMTP_PORT}:${MAIL_SMTP_PORT}
